#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: dev
  labels:
    app: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
#pod tempalte
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        #https://hub.docker.com/_/nginx
        image: nginx:latest
        ports:
        - containerPort: 80